name: ci
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ github.repository }}:latest,${{ github.repository }}:${{github.run_number}}
  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Workflow and Wait
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: lexops
        repo: infra
        workflow_file_name: main.yml
        github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        wait_interval: 0
        wait_workflow: false
        propagate_failure: false
        comment_downstream_url: "HELLO FROM CI"


